name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Challenge 1
      id: challenge-1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: Challenge 2
      id: challenge-2
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 50
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHALLENGE-1_RESULTS: "${{steps.challenge-1.outputs.result}}"
        CHALLENGE-2_RESULTS: "${{steps.challenge-2.outputs.result}}"
      with:
        runners: challenge-1,challenge-2
